name: Publish WebdriverIO TV Labs Service

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Get Package Version
        id: package-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check auth token
        run: npm whoami

      - name: Publish
        run: npm publish --access public --provenance

      - name: Publish notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "VERSION": "${{ steps.package-version.outputs.version }}",
              "PACKAGE_LINK": "https://www.npmjs.com/package/@tvlabs/wdio-service/v/${{ steps.package-version.outputs.version }}",
              "RELEASE_LINK": "https://github.com/tv-labs/wdio-tvlabs-service/releases/tag/v${{ steps.package-version.outputs.version }}",
              "PACKAGE_NAME": "@tvlabs/wdio-service"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PUBLISH_SLACK_WEBHOOK_URL }}
